
name: CI
on:
  pull_request:
    branches: [  ]
jobs:
  add-to-trello:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Attach to Trello Card
    steps:
#     - uses: actions/checkout@v2
    - uses: delivered/attach-to-trello-card-action@v2.0.0
      with: 
        trello-key: $({secrets.software_trello_key})
        trello-token: ${{ secrets.software_trello_token }}
